### ISSUE TITLE
cross model 训练到70000 step后会中止训练，不释放显存，也没有退出，但训练不再进行了。

### ISSUE THREAD

**Issue by suparek** [PaddlePaddle/RocketQA#104]
![image](https://github.com/PaddlePaddle/RocketQA/assets/9245996/65cc32d0-e3bd-43db-a4fb-33038aadf685)

如图所示，是最后的日志，没有报错也没有退出，显存照常占有，但是GPU显示计算已经停止。

**Comment by zhangpeng-HEBUT** [comment]
感觉应该是没显存了吧

**Comment by suparek** [comment]
> 感觉应该是没显存了吧

不是
