### ISSUE TITLE
BM25 of Dureader-retrieval

### ISSUE THREAD

**Issue by tangzhy** [PaddlePaddle/RocketQA#22]
Hi, I wonder what are the hyperparams of k1 and b set in your BM25 baseline?

**Comment by HongyuLi2018** [comment]
Our implementation of BM25 is based on ElasticSearch, we simply use the default hyper-parameters (i.e. b=0.75, k1=1.2).

**Comment by tangzhy** [comment]
Thanks for reply. But out of a bit confusion, I follow the default setting which is exactly the same as yours, and then I found that my BM25 underperforms your results on test cmedqa and covid results.
