### ISSUE TITLE
Test faiss_example cause IndexError in RocketQA docker

### ISSUE THREAD

**Issue by Mr-IT007** [PaddlePaddle/RocketQA#25]
I got IndexError in RocketQA docker when I tested the faiss example under the guidance of [README.md](https://github.com/PaddlePaddle/RocketQA#readme), so I can't do the next step. I'll be grateful if someone can help me. Thx!

![Snipaste_2022-04-26_17-30-44](https://user-images.githubusercontent.com/39551480/165270497-9fffdd09-055c-4c0f-a741-6bfb8a83dad4.png)

![Snipaste_2022-04-26_17-29-51](https://user-images.githubusercontent.com/39551480/165270606-91e24c59-07bf-4815-bb56-0a1e135a35cd.png)

**Comment by Mr-IT007** [comment]
> It seems your paddle version does not match the CUDA device version, so RocketQA model can not run on GPU. If you want to use GPU, this blog may help: https://www.cnblogs.com/faster/p/16012046.html. Or you can set "use_cuda=False".

Sorry, I got another error Segmentation fault when I used CPU version

![e1](https://user-images.githubusercontent.com/39551480/165919245-d9db1d0c-a5d6-4708-8a62-9b0dd6a5cc9b.png)

**Comment by sfwydyc** [comment]
I doubt there's something wrong with your python3 according to the error log.
btw, make sure you install the CPU version Paddle
