### ISSUE TITLE
Test the faiss-example, why the answer rocketqa gived is the whole paragraph, not the short answer!

### ISSUE THREAD

**Issue by Mr-IT007** [PaddlePaddle/RocketQA#36]
I tested the faiss-example, why the answer rocketqa gived was the whole paragraph, not the short answer. Is there something need to set? Compare with the following picture, it seems to be no part of extracting the short answer.

<img width="876" alt="faq1" src="https://user-images.githubusercontent.com/39551480/169229972-a51cdf26-7981-4a40-a942-4bef11282e29.png">

**Comment by sfwydyc** [comment]
Sorry to mislead you, this picture shows the whole process of QA system: Retrieval, Rerank and Extract. RocketQA now released the first 2 steps, retriever and reranker, so the examples only return the whole paragraph.  We will release the answer extractor model soon.
