### ISSUE TITLE
单卡运行无法复现DUreader的baseline结果

### ISSUE THREAD

**Issue by Davion1999** [PaddlePaddle/RocketQA#39]
您好，感谢提供实验代码！
我发现在单卡训练cross encoder的时候，结果与baseline的4*V100各项指标上都差不少，请问有原因吗？

运行环境 Tesla A100 80G，CUDA11.1 Cudnn8.0.5，paddle 2.2.0

提供模型infer的结果：
{"MRR@10": 0.7284, "QueriesRanked": 2000, "recall@1": 0.6410, "recall@50": 0.9175}
自己训练模型的最好结果：
{"MRR@10": 0.7028, "QueriesRanked": 2000, "recall@1": 0.6165, "recall@50": 0.9175}

想问一下这是什么原因？
另，在自己训练时，我们发现使用baseline同样的超参，1.5epoch之后就达到过拟合，请问是单卡的原因吗？

**Comment by Nirvana-2021** [comment]
我也遇到相同问题，请问老哥，这个问题原因找到了么？

**Comment by sfwydyc** [comment]
您好，请问您用的是比赛的基线，还是RocketQA工具中的训练功能呢？

**Comment by Davion1999** [comment]
> 

您好，我使用的是比赛给出的一键运行的基线。此后我又在 Tesla P100 单卡上运行，同样无法达到给出的成绩。

**Comment by quyingqi** [comment]
您好，比赛基线中cross encoder使用的batch size是64*4，模型训练后的效果与超参有一定关系。如果使用单卡训练，可能learning rate也需要同步调整。
