### ISSUE TITLE
cross_encoder

### ISSUE THREAD

**Issue by zemu121** [PaddlePaddle/RocketQA#48]
按照示例中的代码运行cross_encoder的训练，报 中断执行 的错误，显示 corrupted double linked list

**Comment by procedure2012** [comment]
可否把报错的代码段和具体的错误提示贴一下？

**Comment by zemu121** [comment]
WARNING:root:paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
[WARNING] 2022-06-27 06:01:21,485 [       io.py:  721]:	paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
INFO:rocketqa.utils.init:Load pretraining parameters from /root/.rocketqa/zh_dureader_ce/dureader_cross_encoder.
[INFO] 2022-06-27 06:01:24,278 [     init.py:   74]:	Load pretraining parameters from /root/.rocketqa/zh_dureader_ce/dureader_cross_encoder.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::ThreadPoolTempl<paddle::framework::StlThreadEnvironment>::WorkerLoop(int)
1   paddle::framework::InterpreterCore::RunInstructionAsync(unsigned long, std::vector<std::atomic<unsigned long>, std::allocator<std::atomic<unsigned long> > >*, std::vector<std::atomic<unsigned long>, std::allocator<std::atomic<unsigned long> > >*)
2   paddle::framework::Instruction::OpBase() const

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1656309693 (unix time) try "date -d @1656309693" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0xc0710a5220) received by PID 470 (TID 0x7f5c19ff7700) from PID 1896501792 ***]

**Comment by procedure2012** [comment]
看上去和cuda版本有关，目前验证过的环境是CUDA 10.2和cudnn 9.2。

**Comment by zemu121** [comment]
用了CUDA 10.0 ，运行成功了，多谢

**Comment by YYGe01** [comment]
@procedure2012 hi. 问下这个cuda版本的问题, 什么时候可以修复呢,
