### ISSUE TITLE
match函数使用方式

### ISSUE THREAD

**Issue by IamRoBota** [PaddlePaddle/RocketQA#50]
请问既然有encode_query()和encode_para()将问答句子进行编码，为什么match()只支持传入字符串呢？
有方法可以将encode函数编码的到的句子dense representation vectors保存下来，然后在match()的时候重复利用吗？不然效率太低了。
谢谢

**Comment by procedure2012** [comment]
感谢建议。我们后续会尽快加入matching直接处理dense representation vectors的功能。
