### ISSUE TITLE
加载模型

### ISSUE THREAD

**Issue by IamRoBota** [PaddlePaddle/RocketQA#52]
请问rocketqa.load_model("v2_nq_de")时，比如我这里传入的模型名称是v2_nq_de， 那意思是我召回阶段使用dual encoder还是说re-rank阶段使用呢，还是两个阶段都是？谢谢

**Comment by procedure2012** [comment]
每个模型都有一个config文件，里面有一个key “model type”（取值为“duel encode”或则“cross encoder”，不能为空）来指示这个模型是被dual encoder使用还是rerank阶段使用。如果是自己的模型可以根据需要设定这个值，可以参考readme；如果是官方模型，一半带有“de”的是dual encoder的模型，带有“ce”的是rerank使用的模型。

参考 https://github.com/PaddlePaddle/RocketQA/blob/f9626b4978bb3f4d91e44194a25d13c622c3a0fb/rocketqa/rocketqa.py#L108

**Comment by IamRoBota** [comment]
您好，这个了解的。我意思是在load的时候只能填一个模型，但是整个检索过程不是retriever + re-ranker两阶段吗，只加载一个模型的话是指的两个阶段都使用这一个模型？比如rocketqa.load_model("v2_nq_de")，加载了一个dual encoder模型，这个是应用在两个阶段，还是说只用在retriever，然后re-ranker有默认的别的模型？根据您这边论文好像是retriever用dual encoder好，re-ranker用cross encoder好。

**Comment by IamRoBota** [comment]
您好，这个了解的。我意思是在load的时候只能填一个模型，但是整个检索过程不是retriever + re-ranker两阶段吗，只加载一个模型的话是指的两个阶段都使用这一个模型？比如rocketqa.load_model("v2_nq_de")，加载了一个dual encoder模型，这个是应用在两个阶段，还是说只用在retriever，然后re-ranker有默认的别的模型？根据您这边论文好像是retriever用dual encoder好，re-ranker用cross encoder好。

**Comment by procedure2012** [comment]
rocketqa.load_model会根据输入的config加载**一个**dual_encode**或者**cross_encoder的模型。整个检索流程需要加载**两个**模型，一个dual_encoder模型用在召回阶段，一个cross_encode的模型用在精排阶段。

一般流程是这样：
准备阶段：retriever = rocketqa.load("dual_encoder") **and** rerank = rocketqa.load("cross_encoder")
检索阶段：输入query-passage对 --> retriever对qp对做matching，对每个query取出一些候选（比如top100）--> rerank对每个q的候选做matching，根据结果重拍得到最后结果。

我们后续会在readme/examples里添加一些具体的例子

**Comment by IamRoBota** [comment]
好的谢谢
