### ISSUE TITLE
train_dual_encoder 训练效果不好

### ISSUE THREAD

**Issue by fallbernana123456** [PaddlePaddle/RocketQA#55]
我尝试用了一些训练集去训练dual_encoder ，但是效果不好
比如 可怜飞燕倚新妆\t\t《清平调》之二 李白\t\t"一枝秾艳露凝香，云雨巫山枉断肠。借问汉宫谁得似，可怜飞燕倚新妆。"\t0
但是我查询可怜飞燕倚新妆还是查不出来，
在dureader.para里存放了《清平调》之二 李白\t"一枝秾艳露凝香，云雨巫山枉断肠。借问汉宫谁得似，可怜飞燕倚新妆。"
并且使用了训练后的dual_encoder。
我想问下这个是我的训练集没写对吗还是有其他特别的要求
规格是： query \t\t title \t\t para \t 0,1 对吗？

**Comment by procedure2012** [comment]
训练数据集的格式是：
query \t title \t para \t title \t para \t 0 （没有空格）
第一组title+para是正例，第二组title+para是负例，0是固定占位用的。

测试时：
para格式：title \t para （没有空格）对应dureader.para
query格式：query \t - \t - \t 0（没有空格）对应dureader.q

**Comment by fallbernana123456** [comment]
我在做dual_encoder训练的时候
《春兴》武元衡 \t《春兴》武元衡 \t "杨柳阴阴细雨晴，残花落尽见流莺。春风一夜吹乡梦，又逐春风到洛城。" \t《从军行》 \t 杨炯	"烽火照西京，心中自不平。牙璋辞凤阙，铁骑绕龙城。雪暗凋旗画，风多杂鼓声。宁为百夫长，胜作一书生。" \t 0
《春兴》武元衡 \t 《春兴》武元衡 \t "杨柳阴阴细雨晴，残花落尽见流莺。春风一夜吹乡梦，又逐春风到洛城。" \t 《南园》李贺 \t "方领蕙带折角巾，杜若已老兰苕春。南山削秀蓝玉合，小雨归去飞凉云。熟杏暖香梨叶老，草梢竹栅锁池痕。郑公乡老开酒尊，坐泛楚奏吟招魂。" \t 0
用这个做训练语料。 但是搜《春兴》武元衡    春兴  武元衡 都不能命中。但是下面的诗句比如杨柳阴阴细雨晴都能命中。而且很多语料里 模式 《XX》XXXX  都命中不了。能帮看看你们以前遇到过这样的问题吗？

**Comment by procedure2012** [comment]
请问训练集有多大呢？是从头开始训练还是在现有的某个模型上开始训练的？

**Comment by fallbernana123456** [comment]
从头开始和从现有模型上继续训练都不行。

**Comment by fallbernana123456** [comment]
训练集大概由5万条数据
