### ISSUE TITLE
example报错

### ISSUE THREAD

**Issue by Duan-AI-study** [PaddlePaddle/RocketQA#56]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::ThreadPoolTempl<paddle::framework::StlThreadEnvironment>::WorkerLoop(int)
1   paddle::framework::InterpreterCore::RunInstructionAsync(unsigned long, std::vector<std::atomic<unsigned long>, std::allocator<std::atomic<unsigned long> > >*, std::vector<std::atomic<unsigned long>, std::allocator<std::atomic<unsigned long> > >*)
2   paddle::framework::InterpreterCore::CheckGC(paddle::framework::Instruction const&, std::vector<std::atomic<unsigned long>, std::allocator<std::atomic<unsigned long> > >*)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1658907377 (unix time) try "date -d @1658907377" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x9d78) received by PID 7713 (TID 0x7f3ca1d04700) from PID 40312 ***]

**Comment by procedure2012** [comment]
参考https://github.com/PaddlePaddle/RocketQA/issues/51
