### ISSUE TITLE
提供基于 Elasticsearch 的示例

### ISSUE THREAD

**Issue by RussellLuo** [PaddlePaddle/RocketQA#67]
很棒的项目，先赞一个 👍 

请问本项目有打算提供基于 Elasticsearch 的示例吗？Elasticsearch 是业界广泛使用的开源搜索引擎，它 [从 7.3 开始支持向量检索](https://www.elastic.co/cn/blog/text-similarity-search-with-vectors-in-elasticsearch)，当前已经支持 [kNN search](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html)。对于大多数公司而言，使用 Elasticsearch 进行向量检索的核心优势是 **运维零成本**，因为都是现成的中间件。

**Comment by RussellLuo** [comment]
谢谢回复！

我这里提到的 ES，是指作为向量搜索工具（ Faiss 和 JINA）的另一个候选项，整体还是使用 RocketQA 的「召回」和「排序」流程。因为 Faiss 和 JINA 对于大多数公司而言是比较新的工具，用在生产环境会引入新的运维成本，而 ES 基本都是现成的（虽然之前主要用于 “关键词+倒排搜索”，但是现在也支持 “向量搜索” 了）。

**Comment by procedure2012** [comment]
这个暂时还没有计划，不过感谢提供思路😉我们会在后续计划中讨论对ES检索的支持

**Comment by RussellLuo** [comment]
收到。

PS：发起问题后，周末我自己研究了下，已经成功将 RocketQA 接入 ES；如果有需要的话，我可以提供出来（类似新增一个 examples/es_example 示例）😄

**Comment by procedure2012** [comment]
好啊，欢迎提交修改👏可以直接pull request

**Comment by RussellLuo** [comment]
PR 已提交，方便的时候帮忙 Review 下，谢谢！
