### ISSUE TITLE
language other than english and chinese

### ISSUE THREAD

**Issue by amiroft** [PaddlePaddle/RocketQA#76]
thanks for the great work.

I was wondering if we can use this toolkit with PLM in other languages (available in huggingface) and build DPR for that language.
imagine we have appropriate data in that language.

Has anyone had experience developing a model with RocketQA for other languages?

**Comment by procedure2012** [comment]
RocketQA is implemented with Paddle framework and not compatible with huggingface. You can
1. try to convert a PLM ckpt from huggingface version to Paddle version (I think you can find some tools in github)
2. use your own data to train a RocketQA model from scratch (using Ernie as backbone).

**Comment by amiroft** [comment]
thanks for the answer 

maybe I didn't make it completely clear that my main challenge is to know if any PLM can be used [with for example  "v2_marco_ce"  which is cross encoder trained on the MSMARCO dataset(in English) ] since my PLM is in Arabic

**Comment by procedure2012** [comment]
In general, yes. Any PLM can be used in RocketQA as long as it has the same struct as "v2_marco_ce" or "v2_marco_de". You can try to load your PLM and check the log file. If it should have no error message about "various shape".

**Comment by anonymousz97** [comment]
@amiroft have you find the way to solve this? I used a PLM and they said that no var exist (for example : titlepara_encoder...)

**Comment by amiroft** [comment]
> @amiroft have you find the way to solve this? I used a PLM and they said that no var exist (for example : titlepara_encoder...)

No, not yet
 plz let me know if you could do anything about it, I will do the same

**Comment by anonymousz97** [comment]
@amiroft ok sure, but i thinks it is quite hard because when you check the PLM from rocketqa they split the models into multiple weights file. And check the code they load the Ernie model (haven't check the Ernie paper yet) so not easy to convert to their format. @procedure2012 can you provide more details?
