### ISSUE TITLE
Typo in results in README for research/RocketQAv2_EMNLP2021?

### ISSUE THREAD

**Issue by okhat** [PaddlePaddle/RocketQA#8]
Hi! Thanks for the helpful code release.

I was wondering if there was a typo in the MS MARCO and NQ results in research/RocketQAv2_EMNLP2021/README.md

It looks like the results in that table are identical to PAIR, so it might be a simple mistake.

**Comment by LegendaryDan** [comment]
Hi @okhat, 

Yes, it is a typo and it has been corrected. Thanks. 

Jing

**Comment by LegendaryDan** [comment]
> Hi! Thanks for the helpful code release.
> 
> I was wondering if there was a typo in the MS MARCO and NQ results in research/RocketQAv2_EMNLP2021/README.md
> 
> It looks like the results in that table are identical to PAIR, so it might be a simple mistake.

Hi @okhat,

Yes, it is a typo and it has been corrected. Thanks.

Jing
